* Пример кода на ЦП RISC архитектуры (AVR)
** Как собрать и запустить?
*** Вариант 0: Через Arduino IDE
    Необходимо запустить Arduino IDE и открыть файл =risc-avr.ino= из
    текущего каталога.
    
    Далее загрузить программу на подключенный микроконтроллер.

    Результат выполнения программы можно увидеть через монитор порта.
*** Вариант 1: Через Arduino Makefile
    Для сборки и загрузки прошивки можно использовать [[https://github.com/sudar/Arduino-Makefile][Arduino-Makefile]].
    Путь к нему прописан в конце файла =Makefile= в текущем каталоге:
    =/opt/arduino/Arduino.mk=.  Если =Arduino.mk= лежит у вас в другом
    каталоге, то поменяйте =Makefile= соответственно.
    
    Далее компилируем и загружаем программу на микроконтроллер:
#+BEGIN_EXAMPLE
$ make upload
#+END_EXAMPLE
    
    Затем следует подключиться к микроконтроллеру через
    последовательный порт, либо через "Монитор порта" в Arduino IDE,
    либо другим способом -- например, через GNU Screen:
#+BEGIN_EXAMPLE
$ screen /dev/ttyACM0 9600
#+END_EXAMPLE
